sudo: required
language: ruby
services:
- docker
script:
- ls -lah
- docker build -f Dockerfile -t apsl/puput .
- docker-compose -f docker-compose.yml up -d
- docker-compose -f docker-compose.yml ps
- sleep 10
- docker exec -ti dockerpuput_web_1 python manage.py migrate
- docker exec -ti dockerpuput_web_1 python manage.py puput_initial_data
- wget http://localhost:8000/blog/
notifications:
  email:
  - gshark@gmail.com
env:
  global:
  - PUPUT_VERSION=0.4.1
  - secure: TQkOBULVRkar7082KBfBTQ/K+VaVxaaaKkfxj4ZPosWWbHJ5++VnX8Y78igE79U1zqXQVkhAmAFSgq2flmepowUHpxnkM5lZnZ8KLG3tq2OVVdZnkbcnOMOFQbVKoJCxIrkZs7DglIjgexgYWtyw1t700SWXgu8U7JFbTiVw3a93+FCHzpEnnqeJBZPPApXcI4sEbAQirtUrGDfVCOsyrDIAV6eufmaKyqT0kmhYawiWMtkxWO3pfcBbtfUfM8epsJA9HAIfY53wSfKUttvkBmv/ZUHEf8gQlOMip5O/XbsC6epzJ/NgJFPW2bu8xOAc580W3/KCyR56K3T6NDDg+d9K+f1TMhQ5TCS6FuYGnFJ4+jUoSms4viRPzhYmwltZPK479JHsxN9NRBJegGL7+6uqwL0YptGBhP8kWudFrMxbCfZ7Xc3znXnnzyTDgOXCdQi82NL8VbuXmLXtp3WVtymcYD7X4WAAWcN/6mAQ+obZnb3J3gL7R2QEZ0f1BKgzhgFx6RQMZmxEGSh0gCRIZdChUVnizfNMLtDK2Yb6RQ6g3QNNY0wdRnQOtlDWWXki/wLOK6kKnHSapupd7ITIOooi0fjlky+4dLVIRQhFZyslufs/WAL1zyOs/MekECNEuTnZAMiN385DvHZVF5187ZQ1LEOoyUxQifjH59zKtSQ=
  - secure: C43eDkjq4eqikplm7i3lcmtFEHMuLh2qbKtTF79BXL5FxUE4iIlez6fhHzfAw9THb77nbkvSsIpZMu1vCA5nd4P6vV0fELycDdWKW26fzAPCFTGjKwrlZCO/oGGcuxl5El69/L2C3fCPZ0jYTWmEXfpIA+IO5IbqIp/xrmjjTW/iJNWxHDu7e+aY4fFXtqsOHqO4r7qTgnYUVOIvMk2CL5gvKOJ160PfLO+be7eaiWxVTWnZnHBHuwZC4CHQxKjT8OL52PwX4k1zmoKyhtT3nWe0vyo48J5Dtnnks0UZMefZS0aZ3bQSgYwOH0EJ9QsylON4XJ9pc5KAK5mRcfzfj11tkK2ap//wPYOTB2P9N7aeKA1mRWHMxHl3dGaFCBBSkHOt6As1VJ4Ofmg7Tj3GjNJO9udS4NjwsSRS5vJurv+Qn3Q/DHCeq0Eyzhvo5/oIr4p+6jygNV2cAFqlIbKz2I0rRC4e7YzWfjxbVCebYgjy0Roj7TitdvnYWYOVTfA6+4bidXsbRyIEBXAbc53tEc1H4aPdFA0KGaxLrSQ+dp5FZp45eLhJ/EOVOOcsl3HtUiePTIaBU+KYkiJgDOjIbYJgLlsInKsd3wn1hDUiskax+Tvrn0FbFgKm3KX6DQ5OMdoWXYGx2sAEEBag8zGxoecbtDDnW+lLA+ZEHtmKNsI=
  - secure: bI+0y+j2lX/Cepgv3R8JRJ9ZDS+FLSeOcaiVPtskWk9TaSeic/TPnYAprPEZ7Cwk+345hOR9dW/Hxp9Ym/JkPIx5YQBvL0gNXWuEsZg8kPY+4aHko/aWzoSJ8ch4ahFIYkhMAsVXpP1btoudKNUXutgabcZlNfQQIw0zHkxAFEqofz2AscXS+ze1mtSFrP0qwdfax01LWzoPeU96rJy37WOQpX3z5Ts6uRBb4mujz6730rsSrrozPbQwNFccZCNqPJZ532V0WNq/5ZArcQ0mPlUcr06XAD2oYR1lf4qEHQvTqVjhCDUpsAKQuty91oNVyoBiyDIdjfboDHBKz62SxCWe4xb9LwLJzk1iEnmc8kdlu+C6Y058ubpNVQWzrFrCsQE/sRH7x0WsqKA9aT0Puq/8S+8uRIZpBujik9ZM+TdMNhpAhpLm6+MMtcNAAGxUk13CXw3g9SG4UCneXTzc7iDf9rt5wrsKS4Tj2MTpDvMoUESMwh6aUhFC07ULKClmmTBab4KR1xWj4/FgPPr576dd0eFLo9/8lB+sffMnJS1QoBrUFS2l71k/nazcMAOpDYhnqLAL3ODQxadEBqwjH/Ff0JW67U05WSHFLjm8P2LQUJ0r5udRAGHnJEx7v4jCCAcLZY4BXS6kUrgSfefWf/qPGCLtPkThKnMiK+UM4Kc=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $PUPUT_VERSION; fi`
- docker tag apsl/puput apsl/puput:$TAG
- docker push apsl/puput:$TAG


 
